### ISSUE TITLE
Scan failed with traceback

### ISSUE THREAD

**Issue by shizzgar** [ZupIT/horusec#138]
Hello, guys!
Firsly, I want to say, what you have done awesome work! 
UI like a space)

**What happened**:
But I have trouble, while using your horusec-cli tool. 
I was scannig my java project, containig such patter:

```java
    case ZERO_OR_ONE: {
        // If repetition is 0 or 1 (optional), then check if next byte is a 0, which means field is absent or 1, which means
        // field is present. Otherwise, throw an Exception.
        final int nextByte = in.read();
        if (nextByte == -1) {
            throw new EOFException("Unexpected End-of-File when attempting to read Repetition value for field '" + field.getFieldName() + "'");
        }
        if (nextByte == 0) {
            return null;
        }
        if (nextByte != 1) {
            throw new IOException("Invalid Boolean value found when reading 'Repetition' of field '" + field.getFieldName() + "'. Expected 0 or 1 but got " + (nextByte & 0xFF));
    }
```

So, my scan  
`horusec start -p=/horusec/horusec/test-trouble --log-level debug`  
faild after testig mentiond lines with this traceback:
```
user@pc:/horusec/horusec$ horusec start -p="/horusec/horusec/test-trouble" --log-level debug
DEBU[0000] {HORUSEC_CLI} The current configuration for this analysis are:{
  "ConfigFilePath": "/horusec/horusec/horusec-config.json",
  "HorusecAPIUri": "http://localhost:8000",
  "TimeoutInSecondsRequest": 300,
  "IsTimeout": false,
  "TimeoutInSecondsAnalysis": 600,
  "MonitorRetryInSeconds": 15,
  "RepositoryAuthorization": "00000000-0000-0000-0000-000000000000",
  "PrintOutputType": "text",
  "JSONOutputFilePath": "",
  "TypesOfVulnerabilitiesToIgnore": "",
  "FilesOrPathsToIgnore": "**/e2e/**, **/examples/**, **/*.toml, **/*_test.go, **/*_mock.go, **/*README.md, **/development-kit/pkg/enums/engine/advisories/**, **/horusec-lp/.cache/**, **/horusec-lp/public/**, **/deployments/docker-compose*, **/horusec-cli/cmd/horusec/start/analysis/*",
  "ReturnErrorIfFoundVulnerability": false,
  "ProjectPath": "/horusec/horusec/test-trouble",
  "WorkDir": {
    "go": [],
    "netCore": [],
    "ruby": [],
    "python": [],
    "java": [],
    "kotlin": [],
    "javaScript": [],
    "leaks": [],
    "hcl": []
  },
  "FilterPath": "",
  "EnableGitHistoryAnalysis": false,
  "CertInsecureSkipVerify": false,
  "CertPath": "",
  "EnableCommitAuthor": false,
  "RepositoryName": "",
  "FalsePositiveHashes": "a3661718648379e90547895725ad5e1d8021aa48f105ae236427972957a2705f, b17a7ef9ebf374c594700c1bfbf9d3594de68f0fc23af6171269f1f629a8abcf, 0870cfa59cfe7ef087e45762ce1d66cb6fdc85196323fcfae2e90167f242e4b3, df6ef9f4024c6e04bb13de530110e419fefdc0c4370c1e4c04a5a757af799401, 3198f2595d15ba1a01174329c944e3af9f7b3a7af7914e857eb9b82684633236, b85977d0bc430b00f17bc9f431d70b272110afea2549ee41bf03369bf99572d2, 312a4ee6b6b74a8c667e6f907568d9feaa0f0a69091f322abbcdf0562b9a3914, a452ff6d2565d67f118c80866a38a25871606751421347211b8932eb55aed85b, 3a0c53aae9a54d01e97417f2e495ca74c1f8874b0e4805fc622e50f7633838a8",
  "RiskAcceptHashes": "ba56b6e4ac8f790026b82a488c5624d7e2d6f6dd60584a9375c3c8948b608dbf, 2ce87bddc40e085562618f441750eeefe3cffc79d0b05b2e07a98f644c55b2c5, e2eaa19612eed0124b1fec396f8d41381c618c677c2025fc07c1cd0ccbe92b3c, 2b156198552b17c44bab579d68b8cb4204789859ef69a37a7a11e65667cbc66f, 0ffc51a6b0187bec02837cb1e8dddfa05519e83d861af3fbd553bc4d0fbe852d, 4294bf00b848d82c4e012f45e0747996eb75109e089a626af930580a7a179ea4, 4c7ad6feac210f7c447cd65756e08dd5df96d4070545cdc76c5bfaec846b8fe7, de76819bfffe3282f388c1db1421b6378c2a1e450d058d1fb64d6dc1177703b6, f48ffee4aa54549ef31150fbcd75a28e62a17d4b890859dd90cf2f52c34aa936, fa41e0534388707279458969d1dcdb58ff932357660e8855d2bb4170fdbcb391"
} 
DEBU[0000] {HORUSEC_CLI} The file ou folder was ignored to send analysis:[/horusec/horusec/test-trouble/src/.horusec/223de0af-15c0-44f5-b9dd-67aa4a995aa0] 
DEBU[0000] {HORUSEC_CLI} The file ou folder was ignored to send analysis:[/horusec/horusec/test-trouble/src/.horusec/223de0af-15c0-44f5-b9dd-67aa4a995aa0/.horusec] 
DEBU[0000] {HORUSEC_CLI} The file ou folder was ignored to send analysis:[/horusec/horusec/test-trouble/src/.horusec/223de0af-15c0-44f5-b9dd-67aa4a995aa0/bug.java] 
DEBU[0000] {HORUSEC_CLI} The file ou folder was ignored to send analysis:[/horusec/horusec/test-trouble/src/.horusec/223de0af-15c0-44f5-b9dd-67aa4a995aa0/output-223de0af-15c0-44f5-b9dd-67aa4a995aa0.json] 

WARN[0000] {HORUSEC_CLI} When starting the analysis WE SKIP A TOTAL OF 4 FILES that are not considered to be analyzed. To see more details use flag --log-level=debug 

WARN[0000] {HORUSEC_CLI} PLEASE DON'T REMOVE ".horusec" FOLDER BEFORE THE ANALYSIS FINISH! Don’t worry, we’ll remove it after the analysis ends automatically! Project sent to folder in location: [/horusec/horusec/test-trouble/.horusec/56da7ee3-873e-49d3-9e33-d0d2aebce069] 

INFO[0000] Hold on! Horusec still analysis your code. Timeout in: 600s 
DEBU[0000] {HORUSEC_CLI} Running HorusecJava in analysisID: [56da7ee3-873e-49d3-9e33-d0d2aebce069] 
DEBU[0000] {HORUSEC_CLI} Running HorusecLeaks in analysisID: [56da7ee3-873e-49d3-9e33-d0d2aebce069] 
DEBU[0000] {HORUSEC_CLI} Docker pull new image: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-leaks:v0.2.3]] 
DEBU[0000] {HORUSEC_CLI} Docker pull new image: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-java:v0.3.3]] 
DEBU[0000] {HORUSEC_CLI} Docker download new image with success: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-java:v0.3.3]] 
DEBU[0000] {HORUSEC_CLI} Docker download new image with success: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-leaks:v0.2.3]] 
DEBU[0000] {HORUSEC_CLI} Docker create new container: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 containerId:cf8745ade3f37011b40f145bbf56f88de8a04b54a8a22499a869de46c14cc61d image:horuszup/horusec-java:v0.3.3]] 
DEBU[0000] {HORUSEC_CLI} Docker wait container up...[map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 containerId:cf8745ade3f37011b40f145bbf56f88de8a04b54a8a22499a869de46c14cc61d image:]] 
DEBU[0000] {HORUSEC_CLI} Docker create new container: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 containerId:fe383e274bba0bb9ebcf6a2d034f24643c385b5bbc676a0a1d68e1d54febfe0a image:horuszup/horusec-leaks:v0.2.3]] 
DEBU[0000] {HORUSEC_CLI} Docker wait container up...[map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 containerId:fe383e274bba0bb9ebcf6a2d034f24643c385b5bbc676a0a1d68e1d54febfe0a image:]] 
DEBU[0000] {HORUSEC_CLI} Docker read container output: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-leaks:v0.2.3]] 
DEBU[0001] {HORUSEC_CLI} Docker read container output: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-java:v0.3.3]] 
DEBU[0005] {HORUSEC_CLI} Docker Finished analysis with SUCCESS: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-leaks:v0.2.3]] 
DEBU[0005] {HORUSEC_CLI} HorusecLeaks is finished in analysisID: [56da7ee3-873e-49d3-9e33-d0d2aebce069] 
DEBU[0005] {HORUSEC_CLI} When format Output it's Empty![map[tool:HorusecLeaks]] 
DEBU[0006] {HORUSEC_CLI} Docker Finished analysis with SUCCESS: [map[analysisId:56da7ee3-873e-49d3-9e33-d0d2aebce069 image:horuszup/horusec-java:v0.3.3]] 
DEBU[0006] {HORUSEC_CLI} HorusecJava is finished in analysisID: [56da7ee3-873e-49d3-9e33-d0d2aebce069] 
panic: runtime error: slice bounds out of range [168:165]

goroutine 29 [running]:
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters.(*Service).GetCodeWithMaxCharacters(0xc0004ec700, 0xc000fcc0b0, 0xa5, 0xa8, 0xc, 0xc000ffdb80)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/service.go:147 +0x97
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava.(*Formatter).setupVulnerabilitiesSeverities(0xc0004f8880, 0xc000f66400, 0x1, 0x4, 0x0, 0xc00110e370)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava/formatter.go:119 +0x15a
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava.(*Formatter).setOutputInHorusecAnalysis(0xc0004f8880, 0xc000f66400, 0x1, 0x4, 0xc000f66400, 0x1)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava/formatter.go:96 +0x8a
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava.(*Formatter).formatOutput(0xc0004f8880, 0xc00015c400, 0x388, 0xb946d4, 0xb)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava/formatter.go:82 +0x24d
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava.(*Formatter).startHorusecJavaAnalysis(0xc0004f8880, 0x0, 0x0, 0x0, 0x0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava/formatter.go:58 +0x23e
github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava.(*Formatter).StartAnalysis(0xc0004f8880, 0x0, 0x0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/services/formatters/java/horusecjava/formatter.go:44 +0x45
created by github.com/ZupIT/horusec/horusec-cli/internal/controllers/analyser.(*Analyser).detectVulnerabilityJava
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/controllers/analyser/analyser.go:209 +0x85
```

**What you expected to happen**:

I suppose this is not normal behavior.

**How to reproduce it (as minimally and precisely as possible)**:

You should try to scan mentiont pattern.

**Anything else we need to know?**:

I think no

**Environment**:
- Horusec version (use `horusec version`):

user@pc:/horusec/horusec$ horusec version
Actual version installed of the horusec is: v1.4.1

- Operating System:
ubuntu 20.04 lts
- Network plugin / Tool and version (if this is a network-related / tool bug):
No
- Others:
No

**Comment by nathanmartinszup** [comment]
Hi @shizzgar !
Thank you for your feedback, it is of great importance to us. About the error, we are already checking what happened.

**Comment by nathanmartinszup** [comment]
Correction already available in the latest version of the cli (v1.4.2). I will be closing this issue. Thanks again for the report.

**Comment by shizzgar** [comment]
Thanks guys!
I will try it tonight!

**Comment by Alesystem009** [comment]
@shizzgar, can you explain how can I make the correction for this error "goroutine 29 [running]:"?
