### ISSUE TITLE
horusec-messages keeps restarting forever "Restarting (2) x seconds ago"

### ISSUE THREAD

**Issue by py-paulo** [ZupIT/horusec#426]
I went up the service and it worked correctly, but after about 20 minutes UP this specific service is restarting forever without being able to go back.

**What happened**: The *horusec-messages* container is restarting without returning.

**What you expected to happen**: do not keep restarting.

**How to reproduce it (as minimally and precisely as possible)**: I'm not sure, because I followed the tutorial, the difference is that I used the image ``horusec-manager`` to compile from the cloned source code and by default point to the IP of the machine "localhost" -> "172.30.5.30" , since it’s not running localhost, but I don’t see how it could cause problems in the other container.

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`): v1.10.1
- Operating System: Linux 5.4.0-1041-oracle #44-Ubuntu SMP Fri Mar 19 18:12:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

Logs
```
horusec-messages    | time="2021-04-08T13:51:39Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000ad6770
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000ad6700, 0x0, 0xc000029960, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000ad6700, 0x0, 0xc000125ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000165920, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:41Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000acbb20
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000acbab0, 0x0, 0xc0000ff740, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000acbab0, 0x0, 0xc0000adce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc00016b8f0, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:42Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc0005d9650
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc0005d95e0, 0x0, 0xc0005e4280, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc0005d95e0, 0x0, 0xc0000fbce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc0005e0060, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:44Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000b12a10
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000b129a0, 0x0, 0xc0000fe080, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000b129a0, 0x0, 0xc000125ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000b0e030, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:45Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc00014de30
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc00014ddc0, 0x0, 0xc000028900, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc00014ddc0, 0x0, 0xc000125ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc0001314d0, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:48Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000aea770
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000aea700, 0x0, 0xc000029980, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000aea700, 0x0, 0xc000125ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc0001675f0, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:52Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000b44770
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000b44700, 0x0, 0xc0000299e0, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000b44700, 0x0, 0xc0005e5ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000a31890, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:51:59Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000b27180
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000b27110, 0x0, 0xc0000280a0, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000b27110, 0x0, 0xc0000abce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000aa4090, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:52:12Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000134a10
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc0001349a0, 0x0, 0xc0000fe080, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc0001349a0, 0x0, 0xc0000abce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000116180, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:52:38Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000121650
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc0001215e0, 0x0, 0xc0000fe000, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc0001215e0, 0x0, 0xc0000abce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc0001160f0, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages    | time="2021-04-08T13:53:30Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
horusec-messages    | panic: (*logrus.Entry) 0xc000abbb20
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/sirupsen/logrus.(*Entry).log(0xc000abbab0, 0x0, 0xc0000297c0, 0x20)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Log(0xc000abbab0, 0x0, 0xc0005e5ce0, 0x1, 0x1)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
horusec-messages    | github.com/sirupsen/logrus.(*Entry).Panic(...)
horusec-messages    |   /go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000a358f0, 0x0, 0x0, 0x0)
horusec-messages    |   /horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x5)
horusec-messages    |   /horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
horusec-messages    | main.main()
horusec-messages    |   /horusec/horusec-messages/cmd/app/main.go:38 +0x34
horusec-messages exited with code 2
```

**Comment by nathannascimentozup** [comment]
Hi @py-paulo,
the service is restarting is because you need to configure your smtp service credentials. When these credentials are not set in the environment, the service throw this error that you are seeing in the log.

{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank.

**Comment by wiliansilvazup** [comment]
i will close issue for now, if you need help is possible reopen this issue
