### ISSUE TITLE
Install failure on docker-compose w pgSQL (Linux, docker-compose)

### ISSUE THREAD

**Issue by norandom** [ZupIT/horusec#455]
**What happened**:

Service doesn't come / `docker-compose` / `make install`. pgSQL related maybe?

**What you expected to happen**: wanted to set horus up

**How to reproduce it (as minimally and precisely as possible)**:

```
marius@shell:~/horusec/horusec$ make install
docker-compose -f deployments/docker-compose.yaml down -v
WARNING: The HORUSEC_SMTP_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_SMTP_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_BASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_REALM variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_API variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ANALYTIC variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ACCOUNT variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_AUTH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_BASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_REALM variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_MICROFRONTEND_PUBLIC_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_MANAGER_THEME variable is not set. Defaulting to a blank string.
Removing network deployments_default
WARNING: Network deployments_default not found.
docker-compose -f deployments/docker-compose.yaml up -d --build --force-recreate
WARNING: The HORUSEC_SMTP_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_SMTP_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_BASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_KEYCLOAK_REALM variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_API variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ANALYTIC variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ACCOUNT variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_AUTH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_BASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_REALM variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_MICROFRONTEND_PUBLIC_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_MANAGER_THEME variable is not set. Defaulting to a blank string.
Creating network "deployments_default" with the default driver
Pulling rabbit (rabbitmq:3-management)...
3-management: Pulling from library/rabbitmq
01bf7da0a88c: Pull complete
f3b4a5f15c7a: Pull complete
57ffbe87baa1: Pull complete
5ef3ef76b1b5: Pull complete
e9f255817d55: Pull complete
13dc549f3930: Pull complete
a895181f23e6: Pull complete
3d373f7d2d0c: Pull complete
37bf565e5165: Pull complete
e8847c14de68: Pull complete
8ab5f507c5ca: Pull complete
22fedbe2f71d: Pull complete
4c0580b3d32a: Pull complete
Digest: sha256:ea9d5b4a6fdf8e39c56016623d2bfc6e4e79682e1bc1f71b318dc153c64dfb18
Status: Downloaded newer image for rabbitmq:3-management
Pulling postgresql (postgres:12)...
12: Pulling from library/postgres
69692152171a: Pull complete
a31b993d5cc6: Pull complete
f65921886500: Pull complete
b9c1a94e4ca8: Pull complete
435dd99ceb68: Pull complete
d3ee8e88c67c: Pull complete
84b08674f942: Pull complete
7d358e850d3e: Pull complete
12e82e5f286d: Pull complete
305662ca7131: Pull complete
11cd3eebcbbd: Pull complete
9366f2135f89: Pull complete
23c7e66c8792: Pull complete
5c6e2c3cf76b: Pull complete
Digest: sha256:1ad9a00724bdd8d8da9f2d8a782021a8503eff908c9413b5b34f22d518088f26
Status: Downloaded newer image for postgres:12
Pulling horusec-messages (horuszup/horusec-messages:latest)...
latest: Pulling from horuszup/horusec-messages
ba3557a56b15: Pull complete
07a41d445811: Pull complete
Digest: sha256:50961d5368e5f7bee4a9d0ab3cb9757b4241fc85ef7733cd8f5163e52bbd5816
Status: Downloaded newer image for horuszup/horusec-messages:latest
Pulling horusec-auth (horuszup/horusec-auth:latest)...
latest: Pulling from horuszup/horusec-auth
ba3557a56b15: Already exists
c562bb777514: Pull complete
8885246d8322: Pull complete
Digest: sha256:02bee7c7bacb7bfc4b415cfe597645439b45e6fb7cd4fcfc629ab471b466e8bb
Status: Downloaded newer image for horuszup/horusec-auth:latest
Pulling horusec-account (horuszup/horusec-account:latest)...
latest: Pulling from horuszup/horusec-account
ba3557a56b15: Already exists
55e52cc73f82: Pull complete
Digest: sha256:76e9a21b46a1cc0dfc1ab17f06655cb186d38f5c666c3b0bc840f5d10cb0c0c5
Status: Downloaded newer image for horuszup/horusec-account:latest
Pulling horusec-analytic (horuszup/horusec-analytic:latest)...
latest: Pulling from horuszup/horusec-analytic
ba3557a56b15: Already exists
f713edd04e02: Pull complete
Digest: sha256:7fbe3fd5085c3e17a90a3598e9a22aa958a779619b0b5e548bd0e5672318c02f
Status: Downloaded newer image for horuszup/horusec-analytic:latest
Pulling horusec-api (horuszup/horusec-api:latest)...
latest: Pulling from horuszup/horusec-api
ba3557a56b15: Already exists
93b2267c71cb: Pull complete
Digest: sha256:457e2d510b66a3d9f23d643f0a214942ee0ac86a5a08b308ebddd18b165e377a
Status: Downloaded newer image for horuszup/horusec-api:latest
Pulling horusec-webhook (horuszup/horusec-webhook:latest)...
latest: Pulling from horuszup/horusec-webhook
ba3557a56b15: Already exists
5d07384d56e4: Pull complete
Digest: sha256:bb573765688822c7402516595d9ef0d7ec4f54625502d3c7cc1fcc5cc5f07c01
Status: Downloaded newer image for horuszup/horusec-webhook:latest
Pulling horusec-manager (horuszup/horusec-manager:latest)...
latest: Pulling from horuszup/horusec-manager
e95f33c60a64: Pull complete
8b052b3c1a10: Pull complete
a4f5d275d76e: Pull complete
926c236b9574: Pull complete
f049360d30a6: Pull complete
f80e5037dedd: Pull complete
fa5cd8a63cbe: Pull complete
6a589eab1fdf: Pull complete
Digest: sha256:b21d9444ec069d90a7a5d43e1aeec36622addfb4f64f5d563c58a54c01b6f3f2
Status: Downloaded newer image for horuszup/horusec-manager:latest
Creating rabbit          ... done
Creating horusec-manager ... done
Creating postgresql      ...
Creating horusec-messages ...

Creating horusec-messages ... done

ERROR: for postgresql  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Makefile:117: recipe for target 'compose-up' failed
make: *** [compose-up] Error 1
```

**Anything else we need to know?**:

```
marius@shell:~/horusec/horusec$ git show --oneline -s
f1e2fee (HEAD -> master, origin/master, origin/HEAD) Adding nginx tool (#448)
```

**Environment**:

```
marius@shell:~/horusec/horusec$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

pgSQL is up (via docker).

```
marius@shell:~/horusec/horusec$ sudo lsof -i4 | grep -v ssh
COMMAND     PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
rsyslogd   1238 syslog   12u  IPv4   28843      0t0  UDP *:24522
...
docker-pr 19950   root    4u  IPv4 7909177      0t0  TCP *:postgresql (LISTEN)
docker-pr 19979   root    4u  IPv4 7909201      0t0  TCP *:8043 (LISTEN)
docker-pr 20001   root    4u  IPv4 7907757      0t0  TCP *:15672 (LISTEN)
docker-pr 20022   root    4u  IPv4 7910404      0t0  TCP *:amqp (LISTEN)
```

```
marius@shell:~/horusec/horusec$ docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                         PORTS                                                                                                                                                 NAMES
a4f10507a585   horuszup/horusec-messages:latest   "./horusec-messages-…"   16 minutes ago   Restarting (2) 2 seconds ago                                                                                                                                                         horusec-messages
15748bdf8964   rabbitmq:3-management              "docker-entrypoint.s…"   17 minutes ago   Up 16 minutes                  4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   rabbit
4196cd893bde   postgres:12                        "docker-entrypoint.s…"   17 minutes ago   Up 16 minutes                  0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                                             postgresql
ec57579bd5a8   horuszup/horusec-manager:latest    "/docker-entrypoint.…"   17 minutes ago   Up 16 minutes                  80/tcp, 0.0.0.0:8043->8080/tcp, :::8043->8080/tcp                                                                                                     horusec-manager
```

- Horusec version (use `horusec version`): none
- Operating System: Linux
- Network plugin / Tool and version (if this is a network-related / tool bug): docker
- Others:

**Comment by wiliansilvazup** [comment]
Hello @norandom 

After evaluating the output of what happened it appears to be some configuration on your docker.
Please check if this solution can help you
https://github.com/docker/compose/issues/3927#issuecomment-245948736

**Comment by norandom** [comment]
Thank you.

One strep further. That was definitely issue #1. 

I am running into into issue #2 though. 

```
marius@shell:~/horusec/deployments$ docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                          PORTS                                                                                                                                                 NAMES
173ad1cfa4b0   horuszup/horusec-account:latest    "./horusec-account-m…"   4 minutes ago   Up 3 minutes                    0.0.0.0:8003->8003/tcp, :::8003->8003/tcp                                                                                                             horusec-account
7046c7f37783   horuszup/horusec-analytic:latest   "./horusec-analytic-…"   5 minutes ago   Up 4 minutes                    0.0.0.0:8005->8005/tcp, :::8005->8005/tcp                                                                                                             horusec-analytic
fb847b9d1372   horuszup/horusec-auth:latest       "./horusec-auth-main"    5 minutes ago   Up 4 minutes                    0.0.0.0:8006-8007->8006-8007/tcp, :::8006-8007->8006-8007/tcp                                                                                         horusec-auth
19d0bd929d6e   horuszup/horusec-api:latest        "./horusec-api-main"     5 minutes ago   Up 4 minutes                    0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                             horusec-api
3fad9cea0891   horuszup/horusec-webhook:latest    "./horusec-webhook-m…"   5 minutes ago   Up 4 minutes                    0.0.0.0:8008->8008/tcp, :::8008->8008/tcp                                                                                                             horusec-webhook
536f076c912b   horuszup/horusec-messages:latest   "./horusec-messages-…"   5 minutes ago   Restarting (2) 38 seconds ago                                                                                                                                                         horusec-messages
6f2595089821   horuszup/horusec-manager:latest    "/docker-entrypoint.…"   6 minutes ago   Up 5 minutes                    80/tcp, 0.0.0.0:8043->8080/tcp, :::8043->8080/tcp                                                                                                     horusec-manager
8771cd29efc1   postgres:12                        "docker-entrypoint.s…"   6 minutes ago   Up 5 minutes                    0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                                             postgresql
f489d4df0112   rabbitmq:3-management              "docker-entrypoint.s…"   6 minutes ago   Up 5 minutes                    4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   rabbit
```

I take a look at the `horusec-messages`:

```
marius@shell:~/horusec/deployments$ docker logs 536f076c912b
time="2021-05-18T13:01:53Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
panic: (*logrus.Entry) 0xc000c1ea10

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000c1e9a0, 0x0, 0xc000c28020, 0x20)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc000c1e9a0, 0x0, 0xc00012dce0, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanic(0xb3c656, 0x20, 0xbf1460, 0xc000c18030, 0x0, 0x0, 0x0)
	/horusec/development-kit/pkg/utils/logger/logger.go:55 +0x11d
github.com/ZupIT/horusec/horusec-messages/config/mailer.SetUp(0x5, 0x6)
	/horusec/horusec-messages/config/mailer/mailer.go:28 +0x99
main.main()
	/horusec/horusec-messages/cmd/app/main.go:38 +0x34
time="2021-05-18T13:03:08Z" level=panic msg="{MAILER_ERROR} failed to connect" error="password: cannot be blank; username: cannot be blank."
panic: (*logrus.Entry) 0xc000bd1880
```

https://horusec.io/docs/web/installation/install-with-docker-compose/

Is that standard PW not set any more? I grep'ed through some config files, looking for the setting.

**Comment by wiliansilvazup** [comment]
Yeah, 

The horusec-message service really has this problem if you are using the default settings of the docker-compose, [because you have not enabled RabbitMQ](https://horusec.io/docs/tutorials/how-to-enable-disable-messaging-service/) see our documentation to more details, but this configuration is only required if the broker is enable.

We go update documentation with an alert to users setup username and password of the smtp service.
Tnks

**Comment by wiliansilvazup** [comment]
About the horusec manager service, it is not possible to login, check if the settings are correct according to our [documentation tutorial](https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/)

**Comment by norandom** [comment]
Thank you. Problem(s) solved.
