### ISSUE TITLE
Please add feature horusec start without docker

### ISSUE THREAD

**Issue by patsevanton** [ZupIT/horusec#485]
Hello! Thanks for horusec!
I try horusec start in Linux without Docker.

```
horusec start -p .
ERRO[0000] {HORUSEC_CLI} Error when check if requirements it's ok!output:   error=
PANI[0000] {HORUSEC_CLI} Missing required DOCKER in min. version 19.03 to start  error="check the requirements for run and try again"
panic: (*logrus.Entry) 0xc0005189a0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000518930, 0x0, 0xc0000306e0, 0x44)
        /home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc000518930, 0x0, 0xc00115fab0, 0x1, 0x1)
        /home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:331
github.com/ZupIT/horusec-devkit/pkg/utils/logger.LogPanicWithLevel(0xe06802, 0x44, 0x10705c0, 0xc000067220, 0x0, 0x0, 0x0)
        /home/wilian/go/pkg/mod/github.com/!zup!i!t/horusec-devkit@v1.0.7/pkg/utils/logger/logger.go:89 +0x12c
github.com/ZupIT/horusec/internal/controllers/requirements.(*Requirements).ValidateDocker(0xc0011a15a0)
        /home/wilian/go/src/github.com/ZupIT/horusec/internal/controllers/requirements/requirements.go:48 +0x85
github.com/ZupIT/horusec/cmd/app/start.(*Start).validateRequirements(0xc0010a3c20)
        /home/wilian/go/src/github.com/ZupIT/horusec/cmd/app/start/start.go:185 +0x7e
github.com/ZupIT/horusec/cmd/app/start.(*Start).configsValidations(0xc0010a3c20, 0xc000ef1b80, 0x0, 0x0)
        /home/wilian/go/src/github.com/ZupIT/horusec/cmd/app/start/start.go:173 +0xed
github.com/ZupIT/horusec/cmd/app/start.(*Start).startAnalysis(0xc0010a3c20, 0xc000ef1b80, 0xc00115fd80, 0xb57e45, 0xc0011e4adc)
        /home/wilian/go/src/github.com/ZupIT/horusec/cmd/app/start/start.go:159 +0x7a
github.com/ZupIT/horusec/cmd/app/start.(*Start).runE(0xc0010a3c20, 0xc000ef1b80, 0xc0003458e0, 0x0, 0x2, 0x0, 0x0)
        /home/wilian/go/src/github.com/ZupIT/horusec/cmd/app/start/start.go:139 +0x51
github.com/spf13/cobra.(*Command).execute(0xc000ef1b80, 0xc0003458a0, 0x2, 0x2, 0xc000ef1b80, 0xc0003458a0)
        /home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x18deb40, 0x0, 0x189e058, 0xc00007e058)
        /home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/wilian/go/src/github.com/ZupIT/horusec/cmd/app/main.go:65 +0x2d
```
Please add feature horusec start without docker

**Comment by nathanmartinszup** [comment]
Hi @patsevanton.

We already have this feature. 

To run without docker just use the `-D` flag.
Ex.: `horusec start -p . -D`.

Without docker, analysis misses all feedback from the open source tools. So, if possible use it with the docker.

To learn more about horusec and this flag take a look at our [documentation](https://horusec.io/docs/tutorials/how-to-use-horusec-without-docker).

Thanks for your feedback.

**Comment by patsevanton** [comment]
Thanks for answer!

```
horusec start -p . -D

WARN[0000] {HORUSEC_CLI} When starting the analysis WE SKIP A TOTAL OF 62 FILES that are not considered to be analyzed. To see more details use flag --log-level=debug 

WARN[0000] {HORUSEC_CLI} PLEASE DON'T REMOVE ".horusec" FOLDER BEFORE THE ANALYSIS FINISH! Don’t worry, we’ll remove it after the analysis ends automatically! Project sent to folder in location: [/home/apatsev/github/admin/.horusec/a39d40ab-542f-4b1e-adc9-d1d3380d04ec] 

INFO[0000] Hold on! Horusec is still analyzing your code. Timeout in: 600s 
ERRO[0000] {HORUSEC_CLI} Error when list all images enable:   error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
ERRO[0000] {HORUSEC_CLI} Failed to pull docker image -> docker.io/horuszup/horusec-generic:v1.0.1  error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
ERRO[0000] {HORUSEC_CLI} Error when list all images enable:   error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
ERRO[0000] {HORUSEC_CLI} Failed to pull docker image -> docker.io/horuszup/horusec-shell:v1.0.0  error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

horusec  show error.

**Comment by nathanmartinszup** [comment]
The cli was trying to pull the images even with the docker not enabled.

Linked [pull request](https://github.com/ZupIT/horusec/pull/486) fixes the problem.

But even with the error message, the analysis takes place normally, not preventing use.

A new release will be launched after review.

Thank you again for your feedback.
